server:
  port: 10086
spring:
  application:
    name: itcast-eureka #将来作为微服务注入到eureka容器中
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  server:
    eviction-interval-timer-in-ms: 5000 #剔除无效链接的间隔
    enable-self-preservation: false #关闭自我保护状态 （就是你关闭了，他认为你没关闭）

