server:
  port: 8082
mybatis:
  type-aliases-package: com.itheima.pijo
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm?serverTimezone=UTC&useSSL=true
    username: root
    password: root
  application:
    name: cn-itcast-pr
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    fetch-registry: true #服务提供方启东时，会检测是否为ture，ture注册给eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间  续约
    lease-expiration-duration-in-seconds: 15 #过期时间


